services:
  - type: web
    name: owl-app
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
  start: gunicorn --bind 0.0.0.0:$PORT owl.webapp:flask_app
